# Generated by Django 3.2.6 on 2021-11-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='departments',
            new_name='department',
        ),
    ]
